import { Header } from './components/Header'
import './globals.css'
import { Saira } from 'next/font/google'

const saira = Saira({ 
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header/>
      <body className={saira.className}>{children}</body>
    </html>
  )
}
